export const Content = () => {
  return (
    <div className="bg-stone-100">
        <div className="w-4/5 mx-auto py-8">
        <div className="grid grid-cols-2 gap-4 mt-8 items-center">
            <img src="/ip15.jpg" alt="iphone-15" className="rounded-2xl w-full" />
            <p className="text-justify ml-8">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Assumenda fuga aut architecto reprehenderit sapiente quos, quasi optio ipsa, reiciendis nihil magni sed ea alias neque velit laudantium tempore. Aut, blanditiis. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Doloremque ipsa, hic illum provident architecto nam, numquam sunt, officiis blanditiis qui nisi tenetur. Placeat provident repellendus harum ullam iusto cumque qui! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus, dolorem culpa quos nulla quas cupiditate eos alias? Nesciunt, tempore ab? Nemo dolorem beatae fugit quae vero eligendi sequi qui iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur quaerat suscipit facilis et nobis repellat iusto tempora, quibusdam architecto molestias incidunt? Impedit eaque vero in aperiam? Sit, reprehenderit sequi. Quidem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis earum provident repudiandae accusantium deleniti cum nisi exercitationem saepe voluptates maxime. Nesciunt minus earum animi voluptatem praesentium dignissimos cumque itaque fuga. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur eos aperiam impedit possimus nemo, vero incidunt ullam praesentium error repellat excepturi, quidem accusamus laboriosam voluptate sint dolores? Ullam, pariatur quisquam? Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
        </div>
        <div className="grid grid-cols-2 gap-4 my-8 items-center">
            <p className="text-justify mr-8">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Assumenda fuga aut architecto reprehenderit sapiente quos, quasi optio ipsa, reiciendis nihil magni sed ea alias neque velit laudantium tempore. Aut, blanditiis. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Doloremque ipsa, hic illum provident architecto nam, numquam sunt, officiis blanditiis qui nisi tenetur. Placeat provident repellendus harum ullam iusto cumque qui! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus, dolorem culpa quos nulla quas cupiditate eos alias? Nesciunt, tempore ab? Nemo dolorem beatae fugit quae vero eligendi sequi qui iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur quaerat suscipit facilis et nobis repellat iusto tempora, quibusdam architecto molestias incidunt? Impedit eaque vero in aperiam? Sit, reprehenderit sequi. Quidem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis earum provident repudiandae accusantium deleniti cum nisi exercitationem saepe voluptates maxime. Nesciunt minus earum animi voluptatem praesentium dignissimos cumque itaque fuga. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur eos aperiam impedit possimus nemo, vero incidunt ullam praesentium error repellat excepturi, quidem accusamus laboriosam voluptate sint dolores? Ullam, pariatur quisquam? Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            <img src="/ip15.jpg" alt="iphone-15" className="rounded-2xl w-full" />
        </div>
        <div className="grid grid-cols-2 gap-4 mb-8 items-center">
            <img src="/ip15.jpg" alt="iphone-15" className="rounded-2xl w-full" />
            <p className="text-justify ml-8">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Assumenda fuga aut architecto reprehenderit sapiente quos, quasi optio ipsa, reiciendis nihil magni sed ea alias neque velit laudantium tempore. Aut, blanditiis. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Doloremque ipsa, hic illum provident architecto nam, numquam sunt, officiis blanditiis qui nisi tenetur. Placeat provident repellendus harum ullam iusto cumque qui! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus, dolorem culpa quos nulla quas cupiditate eos alias? Nesciunt, tempore ab? Nemo dolorem beatae fugit quae vero eligendi sequi qui iste? Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur quaerat suscipit facilis et nobis repellat iusto tempora, quibusdam architecto molestias incidunt? Impedit eaque vero in aperiam? Sit, reprehenderit sequi. Quidem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis earum provident repudiandae accusantium deleniti cum nisi exercitationem saepe voluptates maxime. Nesciunt minus earum animi voluptatem praesentium dignissimos cumque itaque fuga. Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur eos aperiam impedit possimus nemo, vero incidunt ullam praesentium error repellat excepturi, quidem accusamus laboriosam voluptate sint dolores? Ullam, pariatur quisquam? Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
        </div>
        </div>
    </div>
  )
}